import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import apiExplorerItems from './docs/api-explorer/sidebar';

// Three sidebars mirror the old Mintlify tabs (Home / API Reference / SDKs), but
// each one is autogenerated from the folder tree instead of a hand-kept page
// list. That is deliberate: the Mintlify `docs.json` had drifted and left 32
// pages reachable only by direct URL. Autogeneration means a new `.mdx` shows up
// in the nav the moment it is committed.
//
// Labels and order come from the `_category_.json` in each folder — without them
// Docusaurus shows the raw directory name ("endpoint", "sms", "shop").

const sidebars: SidebarsConfig = {
  guidesSidebar: [
    { type: 'doc', id: 'index', label: 'Introduction' },
    { type: 'autogenerated', dirName: 'examples' },
    { type: 'autogenerated', dirName: 'troubleshooting' },
  ],

  apiSidebar: [
    { type: 'autogenerated', dirName: 'api-reference' },
    { type: 'autogenerated', dirName: 'api' },
  ],

  sdkSidebar: [{ type: 'autogenerated', dirName: 'sdk' }],

  // Generated by docusaurus-plugin-openapi-docs from static/api-reference/openapi.json.
  // Regenerate with `npm run gen-api` after the spec changes.
  apiExplorerSidebar: [
    {
      type: 'category',
      label: 'API Explorer',
      link: { type: 'generated-index', title: 'API Explorer', slug: '/api-explorer' },
      items: apiExplorerItems,
    },
  ],
};

export default sidebars;
